# Generated by Django 5.1.6 on 2025-03-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('authenticated', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('team', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only'), (2, 'Read & Edit')], default=1)),
                ('owner', models.IntegerField(choices=[(2, 'Read & Edit')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('authenticated', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('team', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only'), (2, 'Read & Edit')], default=1)),
                ('owner', models.IntegerField(choices=[(2, 'Read & Edit')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('public', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('authenticated', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only')], default=1)),
                ('team', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Read Only'), (2, 'Read & Edit')], default=1)),
                ('owner', models.IntegerField(choices=[(2, 'Read & Edit')], default=2)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
