# Generated by Django 5.1.6 on 2025-03-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='public',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='like',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='public',
        ),
        migrations.RemoveField(
            model_name='like',
            name='team',
        ),
    ]
