# Generated by Django 5.1.6 on 2025-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.TextField(default='anonymous', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
